version: '3'
services:
  server:
    build:
      context: ./server/
    container_name: server
    command: /usr/app/node_modules/.bin/nodemon src/index.ts
    volumes:
      - ./server/:/usr/app
      - /usr/app/node_modules
    ports:
      - '8282:8080'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
  client:
    build:
      context: ./client/
    command: yarn start
    container_name: client
    env_file: ./client/.env
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - server
    ports:
      - '4001:3000'
